{application,amoveo_mining_pool,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{amoveo_mining_pool_app,[]}},
              {applications,[kernel,ssl,inets,cowboy,stdlib]},
              {env,[]},
              {modules,[amoveo_mining_pool_app,amoveo_mining_pool_sup,
                        mining_pool_server]},
              {maintainers,[]},
              {links,[]}]}.
